version: 0.2
    
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:                                                                 
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install sam --upgrade
      - make lint
  build:
    commands:
      - sam build
	  -	sam deploy --config-file samconfig.toml --no-confirm-changeset
  post_build:
    commands:
      - echo Build completed on `date`