version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stroke-prediction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1urynvzkjcnfr"
s3_prefix = "stroke-prediction"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["StrokeFunction=751467894674.dkr.ecr.us-east-1.amazonaws.com/stroke-prediction-app"]
